services:
  - type: web
    name: app-todo
    env: docker
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: docker build -t app-todo .
    startCommand: docker run -p 3000:3000 app-todo
