services:
  - type: web
    name: app-todo
    env: node
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: npm install
    startCommand: npm start
