name: Build Toto

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
    echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app .
    docker push ${{ secrets.DOCKERHUB_USERNAME }}/app